# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.facts_api import FactsApi


class TestFactsApi(unittest.TestCase):
    """FactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FactsApi()

    def tearDown(self) -> None:
        pass

    def test_apps_app_id_connections_connection_id_facts_get(self) -> None:
        """Test case for apps_app_id_connections_connection_id_facts_get

        List facts.
        """
        pass

    def test_apps_app_id_connections_connection_id_facts_id_get(self) -> None:
        """Test case for apps_app_id_connections_connection_id_facts_id_get

        Get fact details.
        """
        pass

    def test_apps_app_id_connections_connection_id_facts_post(self) -> None:
        """Test case for apps_app_id_connections_connection_id_facts_post

        Issues a fact.
        """
        pass


if __name__ == '__main__':
    unittest.main()
