# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.fact_fact import FactFact

class TestFactFact(unittest.TestCase):
    """FactFact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FactFact:
        """Test FactFact
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FactFact`
        """
        model = FactFact()
        if include_optional:
            return FactFact(
                attestations = [
                    openapi_client.models.entity/attestation.entity.Attestation(
                        body = '', 
                        created_at = '', 
                        id = '', 
                        updated_at = '', 
                        value = '', )
                    ],
                body = '',
                cid = '',
                created_at = '',
                fact = '',
                iat = '',
                id = '',
                iss = '',
                jti = '',
                request_id = '',
                source = '',
                status = '',
                updated_at = '',
                uri = ''
            )
        else:
            return FactFact(
        )
        """

    def testFactFact(self):
        """Test FactFact"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
