# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.healthcheck_api import HealthcheckApi


class TestHealthcheckApi(unittest.TestCase):
    """HealthcheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthcheckApi()

    def tearDown(self) -> None:
        pass

    def test_healthcheck_get(self) -> None:
        """Test case for healthcheck_get

        healthcheck endpoint
        """
        pass


if __name__ == '__main__':
    unittest.main()
