# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.connections_api import ConnectionsApi


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectionsApi()

    def tearDown(self) -> None:
        pass

    def test_apps_app_id_connections_get(self) -> None:
        """Test case for apps_app_id_connections_get

        List connections.
        """
        pass

    def test_apps_app_id_connections_id_delete(self) -> None:
        """Test case for apps_app_id_connections_id_delete

        Deletes an existing connection.
        """
        pass

    def test_apps_app_id_connections_id_get(self) -> None:
        """Test case for apps_app_id_connections_id_get

        Get connection details.
        """
        pass

    def test_apps_app_id_connections_id_put(self) -> None:
        """Test case for apps_app_id_connections_id_put

        Updates a connection.
        """
        pass

    def test_apps_app_id_connections_post(self) -> None:
        """Test case for apps_app_id_connections_post

        Creates a new connection.
        """
        pass


if __name__ == '__main__':
    unittest.main()
