# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.connection_response import ConnectionResponse

class TestConnectionResponse(unittest.TestCase):
    """ConnectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectionResponse:
        """Test ConnectionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectionResponse`
        """
        model = ConnectionResponse()
        if include_optional:
            return ConnectionResponse(
                items = [
                    openapi_client.models.connection/connection.connection.Connection(
                        appid = '', 
                        created_at = '', 
                        id = 56, 
                        name = '', 
                        selfid = '', 
                        updated_at = '', )
                    ],
                page = 56,
                page_count = 56,
                per_page = 56,
                total_count = 56
            )
        else:
            return ConnectionResponse(
        )
        """

    def testConnectionResponse(self):
        """Test ConnectionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
