# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.entity_attestation import EntityAttestation

class TestEntityAttestation(unittest.TestCase):
    """EntityAttestation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityAttestation:
        """Test EntityAttestation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityAttestation`
        """
        model = EntityAttestation()
        if include_optional:
            return EntityAttestation(
                body = '',
                created_at = '',
                id = '',
                updated_at = '',
                value = ''
            )
        else:
            return EntityAttestation(
        )
        """

    def testEntityAttestation(self):
        """Test EntityAttestation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
