# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.notification_system_notification_data_notification import NotificationSystemNotificationDataNotification

class TestNotificationSystemNotificationDataNotification(unittest.TestCase):
    """NotificationSystemNotificationDataNotification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationSystemNotificationDataNotification:
        """Test NotificationSystemNotificationDataNotification
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationSystemNotificationDataNotification`
        """
        model = NotificationSystemNotificationDataNotification()
        if include_optional:
            return NotificationSystemNotificationDataNotification(
                message = '',
                title = '',
                type = ''
            )
        else:
            return NotificationSystemNotificationDataNotification(
        )
        """

    def testNotificationSystemNotificationDataNotification(self):
        """Test NotificationSystemNotificationDataNotification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
