# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.fact_create_fact_request_doc import FactCreateFactRequestDoc

class TestFactCreateFactRequestDoc(unittest.TestCase):
    """FactCreateFactRequestDoc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FactCreateFactRequestDoc:
        """Test FactCreateFactRequestDoc
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FactCreateFactRequestDoc`
        """
        model = FactCreateFactRequestDoc()
        if include_optional:
            return FactCreateFactRequestDoc(
                facts = [
                    openapi_client.models.fact_create_fact_request_doc_facts_inner.fact_CreateFactRequestDoc_facts_inner(
                        group = openapi_client.models.fact_create_fact_request_doc_facts_inner_group.fact_CreateFactRequestDoc_facts_inner_group(
                            icon = '', 
                            name = '', ), 
                        key = '', 
                        source = '', 
                        type = '', 
                        value = '', )
                    ]
            )
        else:
            return FactCreateFactRequestDoc(
        )
        """

    def testFactCreateFactRequestDoc(self):
        """Test FactCreateFactRequestDoc"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
