# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from openapi_client.models.entity_attestation import EntityAttestation
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class FactFact(BaseModel):
    """
    FactFact
    """ # noqa: E501
    attestations: Optional[List[EntityAttestation]] = None
    body: Optional[StrictStr] = None
    cid: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    fact: Optional[StrictStr] = None
    iat: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    iss: Optional[StrictStr] = None
    jti: Optional[StrictStr] = None
    request_id: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    uri: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["attestations", "body", "cid", "created_at", "fact", "iat", "id", "iss", "jti", "request_id", "source", "status", "updated_at", "uri"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FactFact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attestations (list)
        _items = []
        if self.attestations:
            for _item in self.attestations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attestations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of FactFact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attestations": [EntityAttestation.from_dict(_item) for _item in obj.get("attestations")] if obj.get("attestations") is not None else None,
            "body": obj.get("body"),
            "cid": obj.get("cid"),
            "created_at": obj.get("created_at"),
            "fact": obj.get("fact"),
            "iat": obj.get("iat"),
            "id": obj.get("id"),
            "iss": obj.get("iss"),
            "jti": obj.get("jti"),
            "request_id": obj.get("request_id"),
            "source": obj.get("source"),
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at"),
            "uri": obj.get("uri")
        })
        return _obj


