# coding: utf-8

"""
    Joinself restful-client API

    This is the api for Joinself restful client.

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr
from openapi_client.models.request_fact_request import RequestFactRequest
from openapi_client.models.request_request_resource import RequestRequestResource
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class RequestRequest(BaseModel):
    """
    RequestRequest
    """ # noqa: E501
    auth: Optional[StrictBool] = None
    created_at: Optional[StrictStr] = None
    deep_link: Optional[StrictStr] = None
    facts: Optional[List[RequestFactRequest]] = None
    id: Optional[StrictStr] = None
    qr_code: Optional[StrictStr] = None
    resources: Optional[List[RequestRequestResource]] = None
    status: Optional[StrictStr] = None
    typ: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["auth", "created_at", "deep_link", "facts", "id", "qr_code", "resources", "status", "typ", "updated_at"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RequestRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in facts (list)
        _items = []
        if self.facts:
            for _item in self.facts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['facts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in resources (list)
        _items = []
        if self.resources:
            for _item in self.resources:
                if _item:
                    _items.append(_item.to_dict())
            _dict['resources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of RequestRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth": obj.get("auth"),
            "created_at": obj.get("created_at"),
            "deep_link": obj.get("deep_link"),
            "facts": [RequestFactRequest.from_dict(_item) for _item in obj.get("facts")] if obj.get("facts") is not None else None,
            "id": obj.get("id"),
            "qr_code": obj.get("qr_code"),
            "resources": [RequestRequestResource.from_dict(_item) for _item in obj.get("resources")] if obj.get("resources") is not None else None,
            "status": obj.get("status"),
            "typ": obj.get("typ"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


